### ISSUE TITLE
Can you integrate GhostScript too?

### ISSUE THREAD

**Issue by atkulp** [snobu/php-imagick-webapps#3]
I have copied things over and I get imagick to work, but nothing I do gets PDF support.  I've copied the GS libraries to a folder and added it to the path, but I don't know what else to do to tell ImageMagick about them.  The phpinfo() dump does not show PDF or PDFA in the list of supported formats, even though the article (https://blogs.msdn.microsoft.com/azureossds/2015/12/07/php-imagemagick-on-azure-web-apps/) shows it in the screenshot.  I know the GS DLL's themselves aren't redistributable, but if everything else was there along with an empty folder saying "GS LIBRARIES HERE" it would really make a difference!

**Comment by snobu** [comment]
The binaries listed on that blog post are a little different than what i have here, most probably they are compiled with GhostScript support (which explains the screenshot). Just switch to using those and see if GhostScript shows up in your `phpinfo()`. I'm not sure if you still need the GhostScript DLLs in the PATH or it's statically compiled in.. Try without them first.

ImageMagick is more art than science when running on Windows.. but you'll get there with some persistence. Good luck!

**Comment by snobu** [comment]
I have updated the README for PHP 7.0 and made it a little easier to figure out the ImageMagick package dependency.

Looks like PDF and PDFA is built into the binaries that i've used in the PHP 7.0 guide. Give it a try.
