### ISSUE TITLE
PNG does not work

### ISSUE THREAD

**Issue by Himura2la** [snobu/php-imagick-webapps#4]
I use **ImageMagick-6.9.8-3-Q16-x86-dll** and when I try to display an image in the **png** format, I get the following error
```
UnableToLoadModule 'D:\home\site\imagick\coders\IM_MOD_RL_png_.dll': The specified procedure could not be found. @ error/module.c/OpenModule/1282
```

**Comment by snobu** [comment]
Do you have that directory added to the `PATH`?
If you don't, either add it to the XML transform or use my exact folder structure from the repo.

**Comment by Himura2la** [comment]
Yes, I have. JPEG works fine

**Comment by snobu** [comment]
Are you using the exact same binaries as stored in this repo?

**Comment by Himura2la** [comment]
I followed this https://blogs.msdn.microsoft.com/azureossds/2015/12/07/php-imagemagick-on-azure-web-apps/ tutorial and using the up to date version if the lib. But I tried to substitute the PNG dll with no luck. By the way, the tutorial by the link seems to face exactly the same problem (PNG in comment, but GIF in code)

**Comment by snobu** [comment]
Could be. Either try a newer ImageMagick build and match with the appropriate PECL .dll version or just use the binaries from this repo, **but to be honest i don't remember if PNG works here either**.

You're probably better off building on top of a container that already has all the ImageMagick stuff figured out and deploy to [**App Service on Linux**.](https://docs.microsoft.com/en-us/azure/app-service-web/app-service-linux-using-custom-docker-image)

https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=imagemagick+php&starCount=0

**Comment by Himura2la** [comment]
If I had an Azure subscription that allows anything except a simple website and a database (free DreamSpark subscription), I would definitely use docker. The png dll from this repo doesn't work when I try to replace only one dll with it. Maybe I should try replacing the core dlls too, but I'd better use JPEG )) 
Can you please tell more about the PECL dlls? Where can I get other versions?

**Comment by snobu** [comment]
There's a link to PECL in the README: https://pecl.php.net/package/imagick
If you decide to use the bits here, use ALL of them, not just some DLLs. ImageMagick binaries and the PECL binaries **must** match for anything to work right (the PECL .DLL will call function signatures in the CORE DLLs, and the CORE DLLs call into the CODEC DLLs - IM_MOD_*).

EDIT:
Actually i have that wrong. `php_imagick.dll` (PECL) comes with the codecs and the signatures must match the ones in the ImageMagick binaries. This is why nobody should trust a word i say here and go research this on the ImageMagick forums instead.

**Comment by snobu** [comment]
I have updated the README for PHP 7.0 and made it a little easier to figure out the `php_imagick` module dependency. Good luck.

**Comment by Himura2la** [comment]
I got it working, thanks for the good manual)

**Comment by snobu** [comment]
For completeness sake, I tested and PNG does work with the binaries referenced in README.

**Comment by snobu** [comment]
^ for PHP 7.0 that is.
